# Generated by Django 2.2.4 on 2019-09-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofilesinventory',
            name='Text_File',
        ),
        migrations.AddField(
            model_name='audiofilesinventory',
            name='File1',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
