# Generated by Django 2.2.4 on 2019-09-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial1', '0003_auto_20190925_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='audioFilesInventory',
            new_name='FilesInventory',
        ),
    ]
